eval(function(p, a, c, k, e, r) {
  e = function(c) {return (c < a ? '' : e(parseInt(c / a))) + ((c = c % a) > 35 ? String.fromCharCode(c + 29) : c.toString(36))}
  if (!''.replace(/^/, String)) {
    while (c--) r[e(c)] = k[c] || e(c)
    k = [function(e) {return r[e]}]
    e = function() {return '\\w+'}
    c = 1
  }

  while (c--) if (k[c]) p = p.replace(new RegExp('\\b' + e(c) + '\\b', 'g'), k[c])
  return p
}('6 1={e:"5",4:"1d",Q:"16",N:"13"},11={10:l(Y),S:l(0),T:l(2)},E={14:"12",C:"V"};5 l(a){1b(3 a===1.Q)17 a}5 J(a){8.7.J(a)}5 I(a){8.7.I(a)}6 v;5 U(a,b,c){a===E.C?(v(),v=f):3 b!==1.4||3 c!==1.4||3 a!==1.e?r("W 15 y 18"):(v=a,8.7.r(b,c))}6 n;5 B(a,b){h 0!==b&&h 0===l(b)?a("9 X Z"):3 a===1.e?(n=a,8.7.B(b)):(3 a===1.4?n(a):n("9 g"),n=f)}6 p;5 D(a){3 a===1.e?(p=a,8.7.D()):(3 a===1.4?p(a):p("9 g"),p=f)}6 q;5 F(a){3 a===1.e?(q=a,8.7.F()):(3 a===1.4?q(a):q("9 g"),q=f)}6 k;5 G(a){3 a===1.e?(k=a,8.7.G()):(3 a===1.4?k(a):k("9 g"),k=f)}6 j;5 H(a,b,c,d){h 0!==b&&h 0!==c&&3 d===1.N||3 a===1.4?3 a===1.e?(j=a,8.7.H(b,c,d)):(3 a===1.4?j(a):j("9 g"),j=f):a("9 z y K")}6 m;5 L(a,b,c){h 0!==b&&h 0!==c||3 a===1.4?3 a===1.e?(m=a,8.7.L(b,c)):(3 a===1.4?m(w(a)):m("9 g"),m=f):a("9 z y K")}6 i;5 M(a,b){3 a===1.e?3 b===1.4?(i=a,8.7.M(b)):a("9 g x"):(3 a===1.4?i(w(a)):i("9 g"),i=f)}6 o;5 O(a,b){3 a===1.e?3 b===1.4?(o=a,8.7.O(b)):a("9 g x"):(3 a===1.4?o(a):o("9 g"),o=f)}6 u;5 P(a,b){3 a===1.e&&(u=a,8.7.P(b));3 a===1.4&&(u(a),u=f)}6 s;5 19(a,b){3 a===1.e&&(3 b===1.4?(s=a,8.7.1a(b)):a("9 g x"));3 a===1.4&&(a=w(a),r(a),r(R.A(a).1c),s(R.A(a)),s=f)}6 t;5 1e(a){3 a===1.e&&(t=a,8.7.1f());3 a===1.4&&(a=w(a),t(a),t=f)}6 1g;', 62, 79, '|Tag||typeof|String|function|var|control|window|wrong|||||Function|null|request|void|encryptCallback|getAccountAddressCallback|getGoldStoneIDCallback|chainType|getBalanceCallback|getChainIDCallback|decryptCallback|getLanguageCodeCallback|getVersionNameCallback|alert|signedDataCallback|getPermissionsCallBack|signHeaderCallback|confirmEventCallback|decodeURIComponent|message|of|parameters|parse|getChainID|ConfirmEvent|getLanguageCode|CustomizedCommand|getVersionName|getGoldStoneID|getAccountAddress|showShareDashboard|toastMessage|requesting|getBalance|encrypt|Boolean|decrypt|getSignHeader|Int|JSON|BTC|LTC|showAlert|clickedConfirmButton|Wrong|chain|194|type|EOS|ChainType|finished|boolean|FinishedBackEvent|Parameters|number|return|Requesting|getEOSSignedData|getEOSSingedData|if|error|string|getPermissions|getEOSAccountPermissions|backEvent'.split('|'), 0, {}))