eval(function(p, a, c, k, e, r) {
  e = function(c) {return (c < a ? '' : e(parseInt(c / a))) + ((c = c % a) > 35 ? String.fromCharCode(c + 29) : c.toString(36))}
  if (!''.replace(/^/, String)) {
    while (c--) r[e(c)] = k[c] || e(c)
    k = [function(e) {return r[e]}]
    e = function() {return '\\w+'}
    c = 1
  }

  while (c--) if (k[c]) p = p.replace(new RegExp('\\b' + e(c) + '\\b', 'g'), k[c])
  return p
}('7 1={e:"5",4:"S",G:"P",L:"W"},Z={11:l(16),19:l(0),R:l(2)},O={T:"V",F:"Y"};5 l(a){10(3 a===1.G)14 a}5 N(a){8.9.N(a)}7 v;5 Q(a,b,c){a===O.F?(v(),v=f):3 b!==1.4||3 c!==1.4||3 a!==1.e?J("U 1c w X"):(v=a,8.9.J(b,c))}7 j;5 D(a,b){h 0!==b&&h 0===l(b)?a("6 12 13"):3 a===1.e?(j=a,8.9.D(b)):(3 a===1.4?j(a):j("6 g"),j=f)}7 o;5 y(a){3 a===1.e?(o=a,8.9.y()):(3 a===1.4?o(a):o("6 g"),o=f)}7 n;5 A(a){3 a===1.e?(n=a,8.9.A()):(3 a===1.4?n(a):n("6 g"),n=f)}7 q;5 I(a){3 a===1.e?(q=a,8.9.I()):(3 a===1.4?q(a):q("6 g"),q=f)}7 p;5 z(a,b,c,d){h 0!==b&&h 0!==c&&3 d===1.L||3 a===1.4?3 a===1.e?(p=a,8.9.z(b,c,d)):(3 a===1.4?p(a):p("6 g"),p=f):a("6 B w C")}7 k;5 E(a,b,c){h 0!==b&&h 0!==c||3 a===1.4?3 a===1.e?(k=a,8.9.E(b,c)):(3 a===1.4?k(s(a)):k("6 g"),k=f):a("6 B w C")}7 i;5 H(a,b){3 a===1.e?3 b===1.4?(i=a,8.9.H(b)):a("6 g x"):(3 a===1.4?i(s(a)):i("6 g"),i=f)}7 m;5 K(a,b){3 a===1.e?3 b===1.4?(m=a,8.9.K(b)):a("6 g x"):(3 a===1.4?m(a):m("6 g"),m=f)}7 r;5 M(a,b){3 a===1.e&&(r=a,8.9.M(b));3 a===1.4&&(r(a),r=f)}7 u;5 17(a,b){3 a===1.e&&(3 b===1.4?(u=a,8.9.18(b)):a("6 g x"));3 a===1.4&&(a=s(a),u(a),u=f)}7 t;5 1a(a){3 a===1.e&&(t=a,8.9.1b());3 a===1.4&&(a=s(a),t(a),t=f)}7 15;', 62, 75, '|Tag||typeof|String|function|wrong|var|window|control|||||Function|null|request|void|encryptCallback|getChainIDCallback|getBalanceCallback|chainType|decryptCallback|getVersionNameCallback|getLanguageCodeCallback|getAccountAddressCallback|getGoldStoneIDCallback|signHeaderCallback|decodeURIComponent|getPermissionsCallBack|signedDataCallback|confirmEventCallback|of|message|getLanguageCode|getAccountAddress|getVersionName|parameters|requesting|getChainID|getBalance|ConfirmEvent|Int|encrypt|getGoldStoneID|alert|decrypt|Boolean|getSignHeader|toastMessage|CustomizedCommand|number|showAlert|LTC|string|FinishedBackEvent|Wrong|finished|boolean|Requesting|clickedConfirmButton|ChainType|if|EOS|chain|type|return|backEvent|194|getEOSSignedData|getEOSSingedData|BTC|getPermissions|getEOSAccountPermissions|Parameters'.split('|'), 0, {}))