eval(function(p, a, c, k, e, r) {
  e = function(c) {return (c < a ? '' : e(parseInt(c / a))) + ((c = c % a) > 35 ? String.fromCharCode(c + 29) : c.toString(36))}
  if (!''.replace(/^/, String)) {
    while (c--) r[e(c)] = k[c] || e(c)
    k = [function(e) {return r[e]}]
    e = function() {return '\\w+'}
    c = 1
  }

  while (c--) if (k[c]) p = p.replace(new RegExp('\\b' + e(c) + '\\b', 'g'), k[c])
  return p
}('7 1={8:"5",4:"S",E:"P",B:"W"},Z={11:l(N),O:l(0),R:l(2)},H={T:"U",L:"Y"};5 l(a){10(3 a===1.E)14 a}5 G(a){9.e.G(a)}7 q;5 Q(a,b,c){a===H.L?(q(),q=f):3 b!==1.4||3 c!==1.4||3 a!==1.8?J("1a V v X"):(q=a,9.e.J(b,c))}7 k;5 x(a,b){h 0!==b&&h 0===l(b)?a("6 12 13"):3 a===1.8?(k=a,9.e.x(b)):(3 a===1.4?k(a):k("6 g"),k=f)}7 o;5 y(a){3 a===1.8?(o=a,9.e.y()):(3 a===1.4?o(a):o("6 g"),o=f)}7 p;5 D(a){3 a===1.8?(p=a,9.e.D()):(3 a===1.4?p(a):p("6 g"),p=f)}7 n;5 M(a,b,c,d){h 0!==b&&h 0!==c&&3 d===1.B||3 a===1.4?3 a===1.8?(n=a,9.e.M(b,c,d)):(3 a===1.4?n(a):n("6 g"),n=f):a("6 z v A")}7 m;5 C(a,b,c){h 0!==b&&h 0!==c||3 a===1.4?3 a===1.8?(m=a,9.e.C(b,c)):(3 a===1.4?m(t(a)):m("6 g"),m=f):a("6 z v A")}7 j;5 F(a,b){3 a===1.8?3 b===1.4?(j=a,9.e.F(b)):a("6 g w"):(3 a===1.4?j(t(a)):j("6 g"),j=f)}7 i;5 I(a,b){3 a===1.8?3 b===1.4?(i=a,9.e.I(b)):a("6 g w"):(3 a===1.4?i(a):i("6 g"),i=f)}7 s;5 K(a,b){3 a===1.8&&(s=a,9.e.K(b));3 a===1.4&&(s(a),s=f)}7 r;5 15(a,b){3 a===1.8&&(3 b===1.4?(r=a,9.e.16(b)):a("6 g w"));3 a===1.4&&(a=t(a),r(a),r=f)}7 u;5 18(a){3 a===1.8&&(u=a,9.e.19());3 a===1.4&&(a=t(a),u(a),u=f)}7 17;', 62, 73, '|Tag||typeof|String|function|wrong|var|Function|window|||||control|null|request|void|decryptCallback|encryptCallback|getChainIDCallback|chainType|getBalanceCallback|getAccountAddressCallback|getLanguageCodeCallback|getVersionNameCallback|confirmEventCallback|signedDataCallback|signHeaderCallback|decodeURIComponent|getPermissionsCallBack|of|message|getChainID|getLanguageCode|parameters|requesting|Boolean|getBalance|getVersionName|Int|encrypt|toastMessage|CustomizedCommand|decrypt|alert|getSignHeader|ConfirmEvent|getAccountAddress|194|BTC|number|showAlert|LTC|string|FinishedBackEvent|finished|Parameters|boolean|Requesting|clickedConfirmButton|ChainType|if|EOS|chain|type|return|getEOSSignedData|getEOSSingedData|backEvent|getPermissions|getEOSAccountPermissions|Wrong'.split('|'), 0, {}))